### ISSUE TITLE
High memory use

### ISSUE THREAD

**Issue by wezm** [bvaisvil/zenith#10]
zenith seems to use a lot of RAM compared to similar tools:

`zenith -d0 -n0` is using 127.35Mb compared to 5.82Mb for `ytop` and 4Mb for `top`

It seems to be related to the history feature. If I pass `--disable-history` it uses ~18Mb.

**Comment by bvaisvil** [comment]
Thanks for the feedback! The longer zenith runs, the longer the history becomes, the larger the amount of used memory. When history is enabled, it restores the history `vec` from the database. I've got some ideas for improvement here.

**Comment by bvaisvil** [comment]
Reduced memory usage substantially in the latest release. After first run and your DB is migrated it'll use around 30, but after that point, subsequent runs should be around 8 MB.

**Comment by bvaisvil** [comment]
Going to close this for now, please let me know if see any further issues with memory usage.
