### ISSUE TITLE
Temp seems to be wrong

### ISSUE THREAD

**Issue by phumberdroz** [bvaisvil/zenith#101]
➜ sudo powermetrics --samplers smc |grep -i "CPU die temperature"

<img width="640" alt="Screenshot 2021-04-29 at 02 41 53" src="https://user-images.githubusercontent.com/3389721/116489168-9302ea00-a894-11eb-9ffc-2cb3a690c93a.png">

76 vs 140 reported in zenith

**Comment by bvaisvil** [comment]
Thank you for reporting. I see what I did here:

https://github.com/bvaisvil/zenith/blob/master/src/render.rs#L160

` let t: f32 = app.sensors.iter().map(|s| s.current_temp).sum();` 

This was intended to be an average, not a sum.

I've made a change that will now list the temps I have.
