### ISSUE TITLE
PIDs can have more than 5 digits on Linux

### ISSUE THREAD

**Issue by kseistrup** [bvaisvil/zenith#11]
On newer Linux kernels PIDs can have more than five digits:

```bash
$ ps ax -o pid | sort -n | tail -n 3
 671590
 671591
 671592
$ uname -sr
Linux 5.5.10-arch1-1
```

When they do, the `PID` and `USER` columns are no longer separated by a space in `zenith`.

**Comment by bvaisvil** [comment]
Thank you for reporting the issue. 

On linux, zenith now reads /proc/sys/kernel/pid_max and sets the the width the table based upon that value.

From my brief research looks like OS X and BSD can't change these values at run time? Any further information anyone has on this, would be appreciated.
