### ISSUE TITLE
reported virtual memory usage seems overly high and different from top

### ISSUE THREAD

**Issue by rasmuspeders1** [bvaisvil/zenith#14]
Reported virtual memory usage seems extremely high in zenith and is different from what normal top reports.
This with zenith compiled from souce on Fedora 31

![image](https://user-images.githubusercontent.com/1898960/77309828-9e80fa80-6cfd-11ea-8ed3-e082325eddab.png)

![image](https://user-images.githubusercontent.com/1898960/77309835-a0e35480-6cfd-11ea-8306-cc819eb1110c.png)

**Comment by bvaisvil** [comment]
Agreed, that does not look right.

**Comment by rasmuspeders1** [comment]
Nice quick work. This looks fixed on my end now.
