### ISSUE TITLE
failed to run custom build command for `linux-taskstats v0.5.0`

### ISSUE THREAD

**Issue by rafaelfliu** [bvaisvil/zenith#148]
installed using:
`cargo install --features nvidia --git https://github.com/bvaisvil/zenith.git`

running on:
`Ubuntu 22.04.2 LTS`
`rustc 1.78.0 (9b00956e5 2024-04-29)`

**Comment by bvaisvil** [comment]
Is this on AARCH or x64? Also, be great to have the build log.

**Comment by rafaelfliu** [comment]
ah, it's fine. i realized clang is not installed. it's working fine now.

thanks! it's great!

**Comment by rafaelfliu** [comment]
closed
