### ISSUE TITLE
any way to remove leading paths like htop's 'p' key?

### ISSUE THREAD

**Issue by bbigras** [bvaisvil/zenith#15]
With Nix we have very longs paths like this:

![image](https://user-images.githubusercontent.com/24027/77431815-9d120980-6db3-11ea-945e-1aef6f2f2672.png)

htop normal
![image](https://user-images.githubusercontent.com/24027/77431902-bca93200-6db3-11ea-977a-1a5995da922f.png)

htop after pressing the 'p' key
![image](https://user-images.githubusercontent.com/24027/77431939-cd59a800-6db3-11ea-953b-9aafd15e0d10.png)

Would something similar be possible with zenith?

**Comment by bvaisvil** [comment]
added in release 0.8.0.

**Comment by bbigras** [comment]
Thank you very much.

**Comment by bbigras** [comment]
I think the behavior is not exactly the same as htop's.

Would it be possible to strip the leading path instead of hiding them?

For example I have:
![image](https://user-images.githubusercontent.com/24027/78213810-aec57200-7481-11ea-99b5-6f5eaf007289.png)

The process is actually:
![image](https://user-images.githubusercontent.com/24027/78213819-b71dad00-7481-11ea-8eb1-fc0fd601fc5d.png)

Since the path is very long I don't see the `firefox -content` part in "normal mode".

With htop, if I press "p" I get:
![image](https://user-images.githubusercontent.com/24027/78214017-2a272380-7482-11ea-9597-84f8fa65fff5.png)

Which is the part I'm interested in. Right now with zenith the only way to see that part is to hit the 'enter' key.

Very nice work so far btw. zenith is gorgeous.

**Comment by bvaisvil** [comment]
Ahh okay, I understand better now. Should be straight forward to make that change.

> Very nice work so far btw. zenith is gorgeous.

Thanks very much. Been very pleased with the response from everyone so far. Happy that you find it useful!

**Comment by bvaisvil** [comment]
fixed in [0.8.1](https://github.com/bvaisvil/zenith/releases/tag/0.8.1) and [0.82](https://github.com/bvaisvil/zenith/releases/tag/0.8.2)
