### ISSUE TITLE
Height params are not respected

### ISSUE THREAD

**Issue by alshdavid** [bvaisvil/zenith#153]
Running the following command, I want to be able to only see cpu/mem and the process list where the cpu/mem chart is larger than the process list

```bash
zenith -d 0 -n 0 -c 70 -p 30 $@
```

I'd expect to see:
![image](https://github.com/user-attachments/assets/9682a1f0-609a-476a-b35f-31df948e26ba)

However Zenith launches with cpu/mem and process list at 50/50

**Comment by bvaisvil** [comment]
This should be fixed in`master` now.

**Comment by alshdavid** [comment]
Great! Just tested it with a build from `master` and it's working. Thanks for the quick turnaround 🙏
