### ISSUE TITLE
Graphics error on arm64 display

### ISSUE THREAD

**Issue by father-mande** [bvaisvil/zenith#157]
Hi,

Compile on Linux x86_64 (5.13) and arm64 (5.10) of the 0.14.1 (git clone) version

on x86_64 output is OK
on arm64 some empty colored square are displayed (see here after the screen capture)
![zenith_display_arm64](https://github.com/user-attachments/assets/34e6145f-753c-4026-9541-4870a6cf25a7)

I try with different TERM ... no change

any idea ?
Philippe.

**Comment by bvaisvil** [comment]
My best guess - likely the font you're using doesn't support those extended unicode characters

**Comment by father-mande** [comment]
Hi,

Thanks, stupid error in my ssh client configuration (compare to others) ... sorry

Philippe.
