### ISSUE TITLE
[Feature] Laptop Mode

### ISSUE THREAD

**Issue by Byron** [bvaisvil/zenith#2]
If the machine zenith is running on has a battery, show additional information that is most vital to the users of portable computers, namely:

1. charge status in percent
1. time till full or empty, depending on whether the machine is connected to power
1. current amount of power consumption watts

Right now I have to use `battop` for this usecase, which comes with a 'big' TUI with a lot of additional information that is not that useful in practice. It's more of a demo for the underlying library displaying all the information there is about batteries.

Here is the information I usually look at in `battop`:

<img width="990" alt="Screenshot 2020-02-29 at 08 38 31" src="https://user-images.githubusercontent.com/63622/75597367-0b72ed00-5ad0-11ea-86b5-061917b670f7.png">

### Technical Notes

* it looks like on MacOS at least, the OS only provides new battery information every half a minute or so. I usually launch `battop` with `-d 10`, to refresh only every 10 seconds.
* related to the same request in [`bottom`](https://github.com/ClementTsang/bottom/issues/55)

**Comment by bvaisvil** [comment]
I'll definitely looking into adding this.

**Comment by bvaisvil** [comment]
first stab at this in version 0.8.0. Not a full section yet, but top bar widget.

**Comment by Byron** [comment]
A first stab? This is already killing it! I mean, it does everything I would ever want it to do on smallest space! Thanks so much - I don't need battop anymore.
Really, I am baffled and amazed, because…

<img width="115" alt="Screenshot 2020-04-02 at 21 12 59" src="https://user-images.githubusercontent.com/63622/78253340-d28ec380-7526-11ea-9970-5146d695ef9e.png">
<img width="154" alt="Screenshot 2020-04-02 at 21 13 13" src="https://user-images.githubusercontent.com/63622/78253347-d589b400-7526-11ea-8f0a-4623dddf9bf3.png">
<img width="120" alt="Screenshot 2020-04-02 at 21 13 28" src="https://user-images.githubusercontent.com/63622/78253351-d6224a80-7526-11ea-8427-1127e8214899.png">


* …it's context sensitive 
* …shows when actually charging using a power symbol
* …has a battery indicator using a single colored block (I have seen green and yellow), along with battery percentage.
* …shows that watts at which it is charging along with time till full
* …shows the watts at which it is discharging along with time till empty

What else could it possibly be :D? It's done, I am sold!

That said, is there a way to get 'bytes' instead of 'bits' for networking and disk usage?

**Comment by bvaisvil** [comment]
Great! Very happy to hear that it works for you!

Please feel free to add any more issues for requests or any bugs you find.

Re: bits, yeah, that can be done. it auto-scales with byte_unit crate. I suppose this should be configurable on startup...

**Comment by Byron** [comment]
Regarding the bits: I think zenith does it perfectly already, and apparently my network had a very bad day when I thought that I was seeing bits instead of bytes.

Anyway, in the most recent version this is not an issue anymore.
