### ISSUE TITLE
how to search for a process in Zenith?

### ISSUE THREAD

**Issue by gennaro-tedesco** [bvaisvil/zenith#21]
As the title states, how can one search for a specific process in the processes pane? Essentially the equivalent of `htop` search with `/ ` + `F3`.

Or, to rephrase, is it possible to search for a process at all?

**Comment by bvaisvil** [comment]
Just added in version 0.8.0, "f" lets you enter a string to filter the results by. Not exactly the same as a search, but will give similar functionality.

**Comment by gennaro-tedesco** [comment]
Great, I just checkout it out!! Works just fine!

**Comment by bvaisvil** [comment]
Great, going to close this then!
