### ISSUE TITLE
Bar charts do not render correctly with console font

### ISSUE THREAD

**Issue by UbiquitousPhoton** [bvaisvil/zenith#22]
Hi!
This is a project that I would like to get behind, however my first stumbling block is the barcharts do not render properly with a console font (font used by a non-windowing environment on a server)

Does this require patched fonts in order to work?

**Comment by bvaisvil** [comment]
This isn't a use case I've spent a lot of time on yet. 

Perhaps, it is related to this issue: https://github.com/fdehau/tui-rs/issues/56. 

Some fonts can yield strange results. What OS/release etc are you running? Do you happen to know what the font is? It also be great if you could take a screenshot so I can see what sort of rendering problem it is.

I'm not really familiar with patched fonts, so I don't know their use in this context. I think probably that the monospace font doesn't have the characters that make the bar chart.

**Comment by UbiquitousPhoton** [comment]
Font is Terminus, on ubuntu server 16.04

![photo_2020-04-06_14-35-10](https://user-images.githubusercontent.com/39134173/78564097-dca90e80-7813-11ea-92fe-b6df75ee3995.jpg)

**Comment by bvaisvil** [comment]
Thank you for the screenshots. I'll see if there's anything I can do to improve it.

**Comment by oakwhiz** [comment]
![image](https://user-images.githubusercontent.com/1761017/80436478-153c8500-88b4-11ea-913c-78c98d66477f.png)
Having similar issues with PuTTY on Windows.

**Comment by bvaisvil** [comment]
Looks like https://github.com/fdehau/tui-rs/pull/264 may address this issue. I'll work on an update including latest version of `tui-rs`.

**Comment by alexmaco** [comment]
@bvaisvil Is the tui-rs update still in progress ? I'm interested in the performance improvements it can bring. Otherwise, I could do the update and open a PR.
