### ISSUE TITLE
Out of disk space when left to run overnight.

### ISSUE THREAD

**Issue by UbiquitousPhoton** [bvaisvil/zenith#25]
If you leave zenith running long enough, files in ~/zenith/blobs will continue to multiply until basically you run out of space on the partition (150 gig in this case)

This was with zenith 0.7.5 on ubuntu server.

I am presuming from other issues that this can be worked around with --disable-history.

**Comment by bvaisvil** [comment]
Thank you for reporting. Actually, this was previously reported and fixed (#12). Please update to the latest version. I'd recommend removing the ~/.zenith directory before running (if you haven't already). It'll convert the old database, but you'll wait a long time.

**Comment by UbiquitousPhoton** [comment]
Blimey, things are indeed moving fast! Thankyou.
