### ISSUE TITLE
I can't find any histograms

### ISSUE THREAD

**Issue by manithree** [bvaisvil/zenith#3]
Either I'm using zenith wrong, or you are misusing the term histogram.  I can get it to display time series bar charts, but I can't find a single histogram.

https://en.wikipedia.org/wiki/Histogram

Histograms are typically bar charts, but not every bar chart is a histogram.

**Comment by bvaisvil** [comment]
This ... is a good point. I was debating with @dpschmitt earlier today and he convinced that I infact do not have *any* histograms. This however, has given me an idea for some new views.
