### ISSUE TITLE
Behavior of .zenith.lock and usage as pidfile

### ISSUE THREAD

**Issue by alexmaco** [bvaisvil/zenith#34]
`.zenith.lock` seems to work well for preventing 2 copies of zenith from clobbering the same copy of history.

However, I frequently spawn zenith from a remote connection, and when that connection is cut off due to unrelated issues, the running zenith is also killed.

This results in having to manually delete `.zenith.lock` almost on every login to the remote machine.

This does not have to be the case, as the lockfile can be used as a pidfile. That is, it can store identifying information about the running zenith instance, and at startup, zenith can check that indeed the previous instance has been killed without a chance for cleanup, and it can automatically rewrite the lockfile.

This will continue to prevent multiple copies clobbering the history file, while also addressing a common use case for remote work via ssh.

**Comment by bvaisvil** [comment]
Yes, that's a good point. Do you happy to know what signal is sent to running processes when a user's connection is terminated?

**Comment by alexmaco** [comment]
Catching a signal can never be a completely reliable solution, since signal 9 is never received by the process, it just triggers the kernel to kill it immediately. Additionally, there's always the power that can (and sometimes does) go out. So for this to work zenith needs to learn some extra recovery tricks on startup.

I can try to provide an implementation, but I will only be able to test it on linux.

**Comment by bvaisvil** [comment]
Happy to accept a PR. I can test on MacOS.

**Comment by alexmaco** [comment]
I would prefer to do a formatting a clippy-solving PR first. Then I'll work on the lockfile improvements.

**Comment by alexmaco** [comment]
I have a change that implements this behavior at https://github.com/alexmaco/zenith/compare/cleanup...alexmaco:pidfile

I can make a PR with it after #35 is completed.

**Comment by bvaisvil** [comment]
Great, merged #35. Looked at your implementation and it looks nice. Looking forward to the PR.
