### ISSUE TITLE
Highlight the orignal process when go back.

### ISSUE THREAD

**Issue by snippins** [bvaisvil/zenith#38]
I noticed after selecting a process with Enter/Return to view its infos, if I go back to the process list with Esc/b the first process in the list is highlighted instead of the one selected .

This is pretty inconvenient in the case I want to check the information for a list of processes. Thus I suggest to highlight the original selected process.

**Comment by alexmaco** [comment]
I've done a sample implementation of this, available at https://github.com/alexmaco/zenith/tree/same_select_on_back , if you want to evaluate how the ux feels with the change.

After it looks ok, i can open a PR with the change.

**Comment by snippins** [comment]
@alexmaco Thank you very much.

I noticed that I couldn't switch process using arrow keys after filtering with "f". I had workaround that by select the first process and then go back. After that I can switch processes. And after going back I couldn't type right away to change the filter and have to press f.

I can live with it, but the experience definitely feels a little bit "weird".

**Comment by alexmaco** [comment]
Thanks for the testing! Yes, those do sound like problems, i'll fix them and put up a PR.
