### ISSUE TITLE
Running in WSL2: panic about "Not a directory"

### ISSUE THREAD

**Issue by radix** [bvaisvil/zenith#4]
I'm getting this error when I try to start Zenith 0.7.4:

```
❯ zenith
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 20, kind: Other, message: "Not a directory" }', src/libcore/result.rs:1188:5
```

BTW you may want to start compiling with the latest release of Rust, which will include better source locations for errors thrown by `unwrap()`.

**Comment by bvaisvil** [comment]
Thank you for giving it a try and thanks for the report! There was an issue with my fork of sysinfo in WSL. I updated the binary that includes a  (fix)[https://github.com/bvaisvil/sysinfo/commit/99a17605c3189f42f3257c82cd98f9ea039273d7]. However, fixing that revealed another bug in WSL (issue #7).
