### ISSUE TITLE
could not compile `heim-cpu`

### ISSUE THREAD

**Issue by yellowhat** [bvaisvil/zenith#43]
Hi,
I am trying to build zenith-0.9.0 using copr (https://copr.fedorainfracloud.org/coprs/yellowhat/HPC/build/1401683/) but I get the following error:
```
   Compiling heim-cpu v0.1.0-alpha.1 (https://github.com/heim-rs/heim#2629efda)
error: expected `,`
   --> /builddir/.cargo/git/checkouts/heim-d134154c5d7f3f0c/2629efd/heim-cpu/src/sys/linux/freq.rs:135:37
    |
135 |     let frequencies = rt::try_join!(current_freq(&root), max_freq(&root), min_freq(&root));
    |                                     ^^^^^^^^^^^^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

error: could not compile `heim-cpu`.
```

Any ideas?

Thanks

**Comment by bvaisvil** [comment]
Latest release `[0.9.1](https://github.com/bvaisvil/zenith/releases/tag/0.9.1)` fixes the build issue for me. Could you give it a try and let me if it does for you too?

**Comment by yellowhat** [comment]
Thank for the update.
It build fine on CentOS 7, but on 8 and stream I get (https://copr.fedorainfracloud.org/coprs/yellowhat/HPC/build/1415305):
```
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
  --> /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/heim-common-0.1.0-beta.1/src/errors.rs:23:1
   |
23 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/44109
```

Thanks

**Comment by bvaisvil** [comment]
That feature was added in `rustc` [1.40](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-3). I'll change the pre-requisites in the `README.md`.

**Comment by yellowhat** [comment]
For some reason CentOS 8 uses 1.39 and CentOS 7 uses 1.43.

Thanks
