### ISSUE TITLE
Please consider adding back Cargo.lock

### ISSUE THREAD

**Issue by bbigras** [bvaisvil/zenith#44]
Not having a Cargo.lock file prevent us to update the application automatically on NixOS.

**Comment by bvaisvil** [comment]
Thanks for letting me know, that was a mistake. I've updated to include the file, but I'll probably need to update the release for you to be able to use the automated tools?

**Comment by bbigras** [comment]
Yep. :smile:

**Comment by bvaisvil** [comment]
Okay, I'll make a new release later today. I don't think I want to change the existing tag as it may break other packaging systems.

**Comment by bbigras** [comment]
Yeah that makes sense. Thanks!

**Comment by bvaisvil** [comment]
Alright, made the new release. Let me know if there are further build issues!

**Comment by bbigras** [comment]
Thanks!

The `Cargo.lock` file looks like it was generated before the release. NixOS (well one of the rust build function) is picky about that.

I can patch it if you don't want to make another release for now.

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 39b17d3..f95162c 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1613,7 +1613,7 @@ dependencies = [
 
 [[package]]
 name = "zenith"
-version = "0.9.1"
+version = "0.9.2"
 dependencies = [
  "battery",
  "bincode",
```

**Comment by bvaisvil** [comment]
I'll keep this in mind for future releases!
I was planning on making a new release in the next several  days with some new GPU features that I'm still testing. But perhaps a patch is best for now.

**Comment by bbigras** [comment]
Perfect. Thank you very much.
