### ISSUE TITLE
Unable to parse PowerPC64LE CPU info 

### ISSUE THREAD

**Issue by runlevel5** [bvaisvil/zenith#82]
When I run zenith on PowerPC64LE-based Linux, I got following error:

![Screenshot from 2020-10-25 01-49-48](https://user-images.githubusercontent.com/135605/97084684-8fcc3e80-1664-11eb-99e8-a1244bbe6fc4.png)

From my understanding, the error belongs to heim lib. Because I am not 100% confident, I create this ticket to double-check if it might be zenith's issue or not before lodging a new ticket with heim project.

Many thanks

**Comment by bvaisvil** [comment]
Thanks for reporting, I'll take a look.

**Comment by runlevel5** [comment]
@bvaisvil if you need access to a ppc64le dev box to do development or verification, please let me know

**Comment by bvaisvil** [comment]
Indeed, I don't have access to a ppc64le box. However, I'm fairly certain that the underlying issue is with heim as you've surmised.

**Comment by runlevel5** [comment]
@bvaisvil if it is heim, I can close this ticket and lodge one upstream instead. Please help confirm

**Comment by bvaisvil** [comment]
Please make a ticket in `heim`, but let's leave this open because I'll need to update my `heim` dependency once the issue is fixed there.

**Comment by alexmaco** [comment]
Hi @runlevel5 
I've run into a similar issue on 32bit arm machines. I've submitted a PR that was merged into `heim` to fix that. (https://github.com/heim-rs/heim/pull/278)

Since you have access to a ppc machine, you could probably add another case to that arch detection function.

In order to test it locally, you can use a `[replace]` section in `Cargo.toml` to point to a locally modified copy of `heim`.

**Comment by runlevel5** [comment]
I've just lodged a PR upstream https://github.com/heim-rs/heim/pull/286 cc @alexmaco

**Comment by alexmaco** [comment]
@runlevel5 Apologies for going offtopic, but, what machine is that, with 32 ppc64 cores? Looks pretty unique :eyes:

**Comment by runlevel5** [comment]
@alexmaco it's IBM POWER9 (Sforza 8 cores - each core has 4 threads). The motherboard is [Raptor Computing Blackbird](https://www.raptorcs.com/).
