### ISSUE TITLE
Building on Apple Silicon/AArch64/M1

### ISSUE THREAD

**Issue by Byron** [bvaisvil/zenith#88]
I have been trying to get it to work and am using this issue to document what's needed. Eventually this could become a PR.

### Required Changes

* [x] Use latest heim, [this commit](https://github.com/heim-rs/heim/commit/2a6922ead22ef6e095de0be94779c82b5d1d4ca1) works. Unfortunately there is no release yet, and there are test failures.
* [ ] Get [sysinfo linking](https://github.com/GuillaumeGomez/sysinfo/issues/372) fixed - it depends on libc, which has a few PRs/issues regarding Apple/Arm compatibility already.

**Comment by bvaisvil** [comment]
Thanks for starting this, let me know if there is anything I can do to help. I don't have an Apple Silicon machine yet, however.

**Comment by Byron** [comment]
I was able to build zenith with this fix, essentially forcing to use the very latest `libc`:

```patch
diff --git a/Cargo.toml b/Cargo.toml
index 651653e..e3c9e87 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -37,3 +37,6 @@ log = { version = "0.4.*"}
 env_logger = { version = "0.8.1", default-features = false }
 libc = "0.2"
 nvml-wrapper = { version = "0.7.0", optional = true }
+
+[patch.crates-io]
+libc = { git = "https://github.com/rust-lang/libc", version = "0.2" }
```

However, now `helm` is reporting this: `heim_host::sys::unix::platform] Unable to parse CPU architecture from "arm64"`, which might be something to fix in sysinfo itself.

**Comment by richiksc** [comment]
Related: #92. Seems to build succesfully on 0.12.0b with latest `libc 0.2.82`.

**Comment by Byron** [comment]
After pulling the latest master/the new release I can also confirm that `zenith` now builds on Apple Silicon out of the box 🙌.
