### ISSUE TITLE
Outdated Cargo.lock file?

### ISSUE THREAD

**Issue by carlocab** [bvaisvil/zenith#92]
zenith is currently failing to build for Homebrew with Rust 1.49 on Apple Silicon: https://github.com/Homebrew/homebrew-core/pull/68089, https://github.com/Homebrew/homebrew-core/pull/68720

It appears this is due to a stale lock file, causing `cargo install --locked` to pull in dependencies that do not work for zenith on Apple Silicon. Is it possible for the `Cargo.lock` file to be updated? If this could be done with a new release, that would be especially helpful.

I've already tried to use the updated lock file at https://github.com/bvaisvil/zenith/pull/90, but that, too, still leads to a failed build.

Related: https://github.com/Homebrew/homebrew-core/issues/68301

**Comment by bvaisvil** [comment]
Are you trying to build the latest release or the master branch? 

Just curious if making a new release from master would fix the issue or if there would be a further update necessary?

**Comment by carlocab** [comment]
Building the latest release failed, and so did building the latest release except using the `Cargo.lock` file from master. 

I suspect a further update will be necessary. However, I've triggered a build off your master branch to verify this. I'll let you know shortly.

**Comment by carlocab** [comment]
Unfortunately, Homebrew CI refuses to build off something that isn't a tag on GitHub, so I'm unable to test whether building off your master branch is enough. I've tried various hacks to persuade it to attempt a build, but it hasn't worked.

If you don't want to build a new release just yet, it would help if you could tag the head of the master branch so I can build off of it to see.

**Comment by carlocab** [comment]
@richiksc, can you try a build off the master branch here to see if it works?

**Comment by bvaisvil** [comment]
Created a new tag https://github.com/bvaisvil/zenith/releases/tag/0.12.0a

I'm happy to do a release, but just wanted to be sure it'll work before doing so.

**Comment by carlocab** [comment]
Still doesn't work, unfortunately: https://github.com/Homebrew/homebrew-core/pull/68811/checks?check_run_id=1683822324

Updating the `Cargo.lock` file should be enough, I think.

**Comment by richiksc** [comment]
The Cargo.lock file does seem to be updated. Checking the `Cargo.lock` file, it's using the latest version of the `cc` crate, 1.0.66, which supports aarch64-apple-darwin.

Looking at the error from CI:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-arch" "arm64" "-L" "/opt/homebrew/Cellar/rust/1.49.0/lib/rustlib/aarch64-apple-darwin/lib"
...
  = note: Undefined symbols for architecture arm64:
            "_statfs$INODE64", referenced from:
```

I don't know anything about linking or the symbol "$INODE64", so I'm the wrong person to tell you the issue.

**Comment by carlocab** [comment]
>The Cargo.lock file does seem to be updated.

It seems to build fine on CI without the `--locked` flag, though, so it seems like the lock file is specifying an outdated dependency...

**Comment by richiksc** [comment]
Hmm, I'll try to build it locally in an hour or so.

**Comment by bvaisvil** [comment]
I've updated the lockfile once more in this tag: https://github.com/bvaisvil/zenith/releases/tag/0.12.0b

**Comment by richiksc** [comment]
@carlocab Builds succesfully locally with `cargo install --locked --path .` on `0.12.0b == master`.

Thanks @bvaisvil!

**Comment by bvaisvil** [comment]
Awesome! Thank you @richiksc and @carlocab for working on this! 

I'll work on making a release later today/tomorrow.

**Comment by richiksc** [comment]
Yep, our culprit was`libc` as @Byron found out in #88. There are references to $INODE64 in this PR https://github.com/rust-lang/libc/pull/2008/files that fixes support for macOS arm64. These changes were released as part of `libc 0.28.2`, which was released just 4 days ago.

@carlocab If we run into this error again, we'll know it's `libc`.

**Comment by richiksc** [comment]
With the updated Cargo.lock building succesfully, this issue can probably be closed, but there are functional bugs on Apple Silicon: #94.

**Comment by Byron** [comment]
Note that with this change to Cargo.toml, `zenith` seems to work alright. The culprit seems to be the currently released version of `heim` which doesn't know the `arm64` architecture yet. On master, a fix is present though.

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 384fb7b..c1c9097 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -37,3 +37,6 @@ log = { version = "0.4.*"}
 env_logger = { version = "0.8.1", default-features = false }
 libc = "0.2"
 nvml-wrapper = { version = "0.7.0", optional = true }
+
+[patch.crates-io]
+heim = { git = "https://github.com/heim-rs/heim" }
```

**Comment by richiksc** [comment]
@carlocab This issue should be closed.

**Comment by carlocab** [comment]
Thanks everyone!
