### ISSUE TITLE
Using PPA, can't upgrade from v0.11.0 to v0.12.0

### ISSUE THREAD

**Issue by dwvisser** [bvaisvil/zenith#95]
I'm using the amd64 PPA, and my system shows zenith 0.12.0 is available, but when I try to upgrade, I get this message:

```shell
✦ ➜  sudo apt upgrade zenith
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zenith : Depends: libgcc-s1 (>= 4.2) but it is not installable
E: Broken packages
```

**Comment by bvaisvil** [comment]
Thanks for letting me know, I'll take a look. Could be I've not something up correctly.

**Comment by UbioZur** [comment]
Same here on sudo apt install zenith

> Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 zenith : Depends: libgcc-s1 (>= 4.2) but it is not installable
E: Unable to correct problems, you have held broken packages.

Debian buster 10 on amd64 platform

**Comment by bvaisvil** [comment]
@dwvisser What version of debian/ubuntu are you using?

**Comment by dwvisser** [comment]
> @dwvisser What version of debian/ubuntu are you using?

```shell
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 19.3 Tricia
Release:	19.3
Codename:	tricia
```

Linux Mint 19.* is based off of Ubuntu 18.04.

**Comment by bvaisvil** [comment]
@dwvisser Thanks!

This issue is now further complicated as I've learned that bintray (the package host) is [shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/#:~:text=On%20May%201%2C%202021%2C%20the,access%2C%20and%20the%20REST%20API.). 

So I'll have to figure that out, as well.

**Comment by bvaisvil** [comment]
I've added an updated package to my [release](https://github.com/bvaisvil/zenith/releases/tag/0.12.0). I would greatly appreciate it if one or both of you could test the install.

I've tried on Ubuntu(18.04/20.04) and Debian (buster/jessie). My brief searching did not yield and up-to-date linux mint docker to try on. 

Let mw know how the install goes and I'll update the repository. 

Thanks!

**Comment by dwvisser** [comment]
Success. 😄 

```shell
$  sudo apt remove zenith
[sudo] password for ilab-user:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  zenith
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 3,954 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 219699 files and directories currently installed.)
Removing zenith (0.11.0-1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...

$ sudo dpkg -i zenith_0.12.0-1_amd64.deb
Selecting previously unselected package zenith.
(Reading database ... 219687 files and directories currently installed.)
Preparing to unpack zenith_0.12.0-1_amd64.deb ...
Unpacking zenith (0.12.0-1) ...
Setting up zenith (0.12.0-1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
```

**Comment by dwvisser** [comment]
That was actually on a Xubuntu 18.04 VM I use at work. Downloading the package using my browser and installing it with *GDebi* similarly worked on my personal Linux Mint system. 😄

**Comment by bvaisvil** [comment]
@dwvisser Great, glad to hear it works. Are you using `nvidia` support? I'm not sure that I've packaged that correctly.

**Comment by dwvisser** [comment]
I'm not sure. I know my laptop has an Nvidia GPU, but I think I'm using _nouveau_. Is the Nvidia support you refer to for monitoring the GPU? If so, then I think the answer is no.

**Comment by dwvisser** [comment]
Ignore my previous answer. Apparently, I was thinking of my work machine, not my personal laptop, which has AMD graphics that I don't think I'm even using:

```
Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Dell driver: i915 
           v: kernel bus ID: 00:02.0 chip ID: 8086:0416 
           Device-2: AMD Sun XT [Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / R7 M520] 
           vendor: Dell driver: radeon v: kernel bus ID: 01:00.0 chip ID: 1002:6660 
```

**Comment by bvaisvil** [comment]
Okay, great. Thanks for letting me know!
